version: "3.9"

services:
  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: todo-backend:latest
    container_name: todo_backend
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE:-dev}
    depends_on:
      - frontend
    ports:
      - "9091:9091"
    restart: unless-stopped
    networks:
      - football_football-network

  frontend:
    image: todo-frontend:latest
    build:
      context: ./todo-frontend
      args:
        - ENV_FILE=${PROFILE}
      dockerfile: Dockerfile
    container_name: todo_frontend
    volumes:
      - /home/akweh/Documents/todoEnv:/app/env 
    ports:
      - "3001:80"
    restart: unless-stopped
    networks:
      - football_football-network

networks:
  football_football-network:
    external: true
